export default [
    {
        name:"登录",
        path:"/login",
        componentPath:"loginLogic",
    },{
        name:"主界面",
        path:"/main",
        layoutPath:"basicLayout",
        children:[
            {
                name:"用户管理",
                path:"/main/user",
                componentPath:"main/index",
            },
            {
                name:"地区管理",
                path:"/main/region",
                componentPath:"main/index",
            },
            {
                name:"电梯信息维护",
                path:"/main/onlineLift",
                componentPath:"main/index",
            },
            {
                name:"电梯故障处理信息",
                path:"/main/faultDeal",
                componentPath:"main/index",
            },
            {
                name:"电梯批量登记",
                path:"/main/registration",
                componentPath:"main/index",
            },
            {
                name:"电梯维护信息",
                path:"/main/maintenance",
                componentPath:"main/index",
            },
        ]
    }
]


